name: "Phpstan"

on:
  pull_request:
  workflow_dispatch:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 9 * * 1"

jobs:
  phpstan:
    name: "Phpstan"
    uses: contributte/.github/.github/workflows/phpstan.yml@master
    with:
      php: "8.4"
